services:
  cassandra:
    image: cassandra:5
    container_name: javify-cassandra
    restart: always
    ports:
      - "9042:9042"
    volumes:
      - cassandra_data:/var/lib/cassandra

volumes:
  cassandra_data:
